site_name: napari-pybasic
site_description: PyBaSiC illumination correction for napari
site_author: Tim Morello

theme: readthedocs


repo_url: https://github.com/tdmorello/napari-pybasic

pages:
- Home: index.md
