site_name: napari-basicpy
site_description: BaSiCPY illumination correction for napari
site_author: Tim Morello

theme: readthedocs

repo_url: https://github.com/tdmorello/napari-basicpy

pages:
  - Home: index.md
