[build-system]
requires = ["setuptools>=42.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/napari_basicpy/_version.py"

[tool.isort]
"line_length" = 88
"profile" = "black"

[tool.black]
"line_length" = 88
